<a href="https://colab.research.google.com/github/silverstar0727/study-/blob/master/Pytorch_%EC%9E%85%EB%AC%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch
!pip install torchvision

## Tensors
Tensor는 numpy의 ndarray와 비슷하다고 생각하면 됨, GPU를 사용한 연산의 가속도 가능하다는 장점이 존재함


In [1]:
from __future__ import print_function
import torch

In [2]:
# 초기화되지 않은 5x3행렬을 생성
x = torch.empty(5, 3)
print(x)

## 초기화 되지 않은 행렬이 선언 되었으나, 사용 전엔 명확한 값이 아닌, 지금 할당된 메모리에 존재하던 값들이
## 초기값으로 주어짐

tensor([[1.4551e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 5.3412e-36]])


In [3]:
# 무작위로 5x3행렬을 생성
x = torch.rand(5, 3)
print(x)

tensor([[0.6929, 0.7344, 0.6247],
        [0.7171, 0.0145, 0.9824],
        [0.0627, 0.8814, 0.6032],
        [0.4333, 0.0586, 0.6725],
        [0.1310, 0.0363, 0.6798]])


In [4]:
# 데이터 타입이 long인 0으로 채워진 5x3 행렬을 생성
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 데이터를 통해 tensor를 직접생성(list to tensor)
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 기존 tensor를 바탕으로 새로운 tensor를 생성 
x = x.new_ones(5, 3, dtype = torch.double)
print(x)
x = torch.randn_like(x, dtype = torch.float) # 앞서 설정한 x와 동일한 크기의 random한 값을 설정(Override)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0498,  0.5448, -0.0371],
        [ 0.7555, -1.4575,  0.3132],
        [ 1.1262, -0.4757, -0.7263],
        [ 0.5528,  0.8034, -0.7497],
        [ 1.1329,  1.0108,  0.2765]])


In [7]:
# 행렬의 크기를 구함
print(x.size()) # 튜플타입을 아웃풋으로

torch.Size([5, 3])


## 연산(Operations)

In [8]:
# 덧셈1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1713,  0.7952,  0.4916],
        [ 1.4039, -1.4186,  0.9019],
        [ 1.3935,  0.4519, -0.2124],
        [ 1.1164,  1.7243, -0.1933],
        [ 1.7018,  1.1943,  0.6182]])


In [9]:
# 덧셈2
print(torch.add(x, y))

tensor([[ 1.1713,  0.7952,  0.4916],
        [ 1.4039, -1.4186,  0.9019],
        [ 1.3935,  0.4519, -0.2124],
        [ 1.1164,  1.7243, -0.1933],
        [ 1.7018,  1.1943,  0.6182]])


In [10]:
# 덧셈을 빈 행렬을 이용하여 아웃풋으로 저장
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 1.1713,  0.7952,  0.4916],
        [ 1.4039, -1.4186,  0.9019],
        [ 1.3935,  0.4519, -0.2124],
        [ 1.1164,  1.7243, -0.1933],
        [ 1.7018,  1.1943,  0.6182]])


In [11]:
# 덧셈3 in-place방식 (기존의 것을 없애고 더한 값으로 재저장)
# in-place 방식으로 tensor를 변경하면 _가 붙음
y.add_(x)
print(y)

tensor([[ 1.1713,  0.7952,  0.4916],
        [ 1.4039, -1.4186,  0.9019],
        [ 1.3935,  0.4519, -0.2124],
        [ 1.1164,  1.7243, -0.1933],
        [ 1.7018,  1.1943,  0.6182]])


In [12]:
# tensor의 size나 shape를 변경하고 싶을 땐 tensor.view를 사용
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1은 다른 차원에서 유추(2차원에서 8개이니 1차원에서는 2여야만 함)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
#tensor의 값이 단일하다면 .item()을 통해 값을 얻을 수 있음
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8113])
0.8113411068916321


## Torch의 tensor를 numpy 배열로 변환
tensor와 numpy의 배열은 같은 메모리 공간을 공유하기 때문에 하나가 바뀌면 이를 참조한 다른하나도 바뀐다.

In [14]:
# a는 텐서
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
# b는 넘파이
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
# b도 a에 따라 1씩 증가하는 형태가 되나, numpy의 형태는 유지
a.add_(1)
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


## numpy배열을 Torch의 tensor로 변환하기

In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA tensors
.to의 메소드를 이용하여 tensor를 다른 장치로 옮길 수 있다

In [18]:
## CUDA의 사용이 가능한 환경에서만 실행됨
if torch.cuda.is_available():
  device = torch.device('cuda')
  y = torch.ones_like(x, device = device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to('cpu', torch.double))

tensor([1.8113], device='cuda:0')
tensor([1.8113], dtype=torch.float64)
